### ISSUE TITLE
Milestone Planning

### ISSUE THREAD

**Issue by Tugark** [gipfeli-io/documentation#3]
https://docs.gipfeli.io/general/milestones-planning

# Review

- [x] Documentation is written
- [x] Documentation is reviewed
- [x] Build is successful
- [x] Deployment to production works
